const games=[
{id:"multi-vegas-81",name:"Multi Vegas 81",tag:"CLASSIC",type:"hot",rtp:90,min:1,max:250,theme:"mv81",layout:"4x3",lines:81,image:"mv81/multi-vegas-81.svg",symbols:["CHERRY","DOLLAR","ORANGE","PLUM","BELL","GRAPES","MELON","SEVEN","WILD"],payouts:{CHERRY:{3:1,4:2},DOLLAR:{3:1,4:3},ORANGE:{3:1,4:3},PLUM:{3:1,4:3},BELL:{3:1,4:3},GRAPES:{3:2,4:20},MELON:{3:4,4:40},SEVEN:{3:7,4:80}}},
{id:"vinewood",name:"Vinewood Nights",tag:"NEW",type:"new",rtp:96,min:10,max:3000,theme:"pink",layout:"5x4",lines:40,image:"vinewood.jpg",symbols:["STAR","CLAP","GEM","CHAMP","SEVEN"],payouts:{SEVEN:40,GEM:20,STAR:12,CLAP:8,CHAMP:5}},
{id:"cash-cartel",name:"Cash Cartel",tag:"POPULAR",type:"hot",rtp:95,min:25,max:7500,theme:"gold",layout:"5x3",lines:25,image:"cash-cartel.jpg",symbols:["CASH","GOLD","GUN","CAR","SEVEN"],payouts:{SEVEN:50,CASH:30,GOLD:15,GUN:8,CAR:5}},
{id:"diamond",name:"Diamond Rush",tag:"JACKPOT",type:"vip",rtp:94,min:50,max:10000,theme:"blue",layout:"6x4",lines:"MEGAWAYS",image:"diamond-rush.jpg",symbols:["DIAMOND","CLUB","ACE","COIN","SEVEN"],payouts:{SEVEN:60,DIAMOND:35,COIN:15,ACE:8,CLUB:5}},
{id:"lucky",name:"Lucky Sevens",tag:"CLASSIC",type:"hot",rtp:95,min:10,max:5000,theme:"red",layout:"3x2",lines:5,image:"lucky-sevens.jpg",symbols:["SEVEN","BAR","CHERRY","BELL","LEMON"],payouts:{SEVEN:50,BAR:20,CHERRY:8,BELL:5,LEMON:3}},
{id:"street",name:"Street Racers",tag:"NEW",type:"new",rtp:96,min:10,max:4000,theme:"cyan",layout:"5x3",lines:30,image:"street-racers.jpg",symbols:["RACE","FLAG","TURBO","FIRE","SEVEN"],payouts:{SEVEN:45,RACE:25,FIRE:12,FLAG:7,TURBO:4}},
{id:"high-roller",name:"High Roller",tag:"VIP",type:"vip",rtp:93,min:100,max:20000,theme:"blackgold",layout:"4x3",lines:"3x3 BONUS",image:"high-roller.jpg",symbols:["ACE","DICE","CASH","ROYAL","SEVEN"],payouts:{SEVEN:75,CASH:30,ROYAL:15,DICE:10,ACE:5}},
{id:"fruits",name:"Blazing Fruits",tag:"POPULAR",type:"hot",rtp:96,min:5,max:2500,theme:"orange",layout:"5x4",lines:20,image:"blazing-fruits.jpg",symbols:["CHERRY","MELON","LEMON","ORANGE","SEVEN"],payouts:{SEVEN:35,MELON:15,CHERRY:8,ORANGE:5,LEMON:3}},
{id:"mafia",name:"Mafia Fortune",tag:"EXCLUSIVE",type:"vip",rtp:94,min:50,max:15000,theme:"mafia",layout:"4x3",lines:15,image:"mafia-fortune.jpg",symbols:["BOSS","CASH","CAR","WHISKY","SEVEN"],payouts:{SEVEN:70,CASH:30,BOSS:15,WHISKY:8,CAR:5}},
{id:"ocean",name:"Ocean Drive",tag:"CHILL",type:"new",rtp:96,min:10,max:5000,theme:"ocean",layout:"6x3",lines:50,image:"ocean-drive.jpg",symbols:["PALM","WAVE","ROAD","GEM","SEVEN"],payouts:{SEVEN:45,GEM:20,WAVE:12,PALM:7,ROAD:4}}
];

let balance=10000,current=null,bet=100,spinning=false,sound=true,history=[],dailyClaimed=false;
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString("cs-CZ");

function renderGames(filter="all"){
 $("gameGrid").innerHTML=games.filter(g=>filter==="all"||g.type===filter).map(g=>`
 <button class="game-card theme-${g.theme}" onclick="openGame('${g.id}')">
  <div class="card-art"><img src="assets/games/${g.image}" alt="${g.name}"><div class="card-shade"></div><div class="layout-badge">${g.layout} • ${g.lines} LINES</div><div class="badge badge-${g.type}">${g.tag}</div></div>
  <div class="card-info"><div><b>${g.name}</b><small>${g.min}–${fmt(g.max)} TOKENS • ${g.layout}</small></div><span class="play-arrow">→</span></div>
 </button>`).join("");
}
document.querySelectorAll(".filter").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");renderGames(btn.dataset.filter)}));

function showLobby(){closeGame();closePanel();window.scrollTo({top:0,behavior:"smooth"})}
function scrollToGames(){$("gamesSection").scrollIntoView({behavior:"smooth"})}
function addTokens(){balance+=10000;updateBalances();toast("＋10,000 TOKENŮ PŘIDÁNO");}
function openGame(id){
 current=games.find(g=>g.id===id);bet=Math.max(current.min,Math.min(current.max,bet));
 $("gameTitle").textContent=current.name.toUpperCase();$("gameTag").textContent=current.tag+" • "+current.layout+" • "+current.lines+" LINES";$("gameRtp").textContent=`RTP ${isMV81() ? 90 : current.rtp}%`;
 $("neonSign").innerHTML=current.name.split(" ").slice(0,-1).join(" ")+"<br><span>"+current.name.split(" ").at(-1).toUpperCase()+"</span>";
 $("machine").className="machine machine-"+current.theme;$("machineScene").className="machine-scene scene-"+current.theme;
 buildReels();updateBetUI();setReels(randomReels());$("machineResult").textContent="READY TO SPIN";$("gameOverlay").classList.remove("hidden");
}
function closeGame(){if(!spinning)$("gameOverlay").classList.add("hidden")}
function buildReels(){
 const match=current.layout.match(/(\d+)x(\d+)/);const cols=+match[1],rows=+match[2];const frame=$("reelFrame");frame.innerHTML="";
 frame.style.setProperty("--cols",cols);frame.style.setProperty("--rows",rows);
 for(let i=0;i<cols*rows;i++){const el=document.createElement("div");el.className="reel";el.dataset.index=i;frame.appendChild(el)}
}

const MV81_PAYOUT_FACTOR=0.9/0.95;
const MV81_PATTERNS_3=Array.from({length:27},(_,n)=>[Math.floor(n/9)%3,Math.floor(n/3)%3,n%3]);
const MV81_PATTERNS_4=Array.from({length:81},(_,n)=>[Math.floor(n/27)%3,Math.floor(n/9)%3,Math.floor(n/3)%3,n%3]);
const MV81_SYMBOLS={
 CHERRY:{file:"cherry.svg",label:"CHERRY"},
 DOLLAR:{file:"dollar.svg",label:"$"},
 ORANGE:{file:"orange.svg",label:"ORANGE"},
 PLUM:{file:"plum.svg",label:"PLUM"},
 BELL:{file:"bell.svg",label:"BELL"},
 GRAPES:{file:"grapes.svg",label:"GRAPES"},
 MELON:{file:"melon.svg",label:"MELON"},
 SEVEN:{file:"seven.svg",label:"7"},
 WILD:{file:"wild.svg",label:"MULTI WILD"}
};
function isMV81(){return current?.id==="multi-vegas-81"}
function symbolMarkup(s){
 if(isMV81()){
   const q=MV81_SYMBOLS[s];
   return `<span class="slot-symbol mv81-symbol" data-symbol="${s}"><img src="assets/games/mv81/${q.file}" alt="${q.label}"></span>`;
 }
 return `<span class="slot-symbol sym-${s.toLowerCase()}">${s}</span>`;
}
function setReels(r){
  const cells=[...document.querySelectorAll("#reelFrame .reel")];
  cells.forEach((el,i)=>{
    const symbol=r[i];
    el.innerHTML=symbolMarkup(symbol);
    el.dataset.symbol=symbol || "";
  });
}
function randomReels(){
 const n=+current.layout.split("x")[0]*+current.layout.split("x")[1];
 return Array.from({length:n},()=>current.symbols[Math.floor(Math.random()*current.symbols.length)]);
}
const MV81_REEL_STRIPS=[["ORANGE","DOLLAR","MELON","DOLLAR","ORANGE","BELL","BELL","BELL","ORANGE","PLUM","PLUM","CHERRY","DOLLAR","DOLLAR","ORANGE","BELL","BELL","WILD","DOLLAR","BELL","PLUM","ORANGE","ORANGE","PLUM","WILD","PLUM","ORANGE","CHERRY","CHERRY","PLUM","DOLLAR","MELON","PLUM","ORANGE","ORANGE","DOLLAR","PLUM","BELL","DOLLAR","ORANGE","BELL","WILD","DOLLAR","BELL","DOLLAR","DOLLAR","PLUM","ORANGE","DOLLAR","BELL","PLUM","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","DOLLAR","ORANGE","BELL","DOLLAR","CHERRY","BELL","BELL","DOLLAR","DOLLAR","DOLLAR","CHERRY","BELL","PLUM","DOLLAR","GRAPES","DOLLAR","DOLLAR","DOLLAR","CHERRY","PLUM","PLUM","DOLLAR","DOLLAR","PLUM","MELON","DOLLAR","BELL","ORANGE","PLUM","MELON","WILD","PLUM","CHERRY","DOLLAR","PLUM","BELL","GRAPES","DOLLAR","PLUM","CHERRY","CHERRY","MELON","GRAPES","WILD","DOLLAR","GRAPES","DOLLAR","PLUM","GRAPES","BELL","DOLLAR","PLUM","DOLLAR","PLUM","ORANGE","GRAPES","ORANGE","DOLLAR","GRAPES","DOLLAR","BELL","ORANGE","MELON","BELL","GRAPES","ORANGE","BELL","DOLLAR","BELL","WILD","PLUM","PLUM","CHERRY","BELL","DOLLAR","PLUM","DOLLAR","BELL","PLUM","BELL","CHERRY","BELL","DOLLAR","BELL","GRAPES","DOLLAR","ORANGE","WILD","ORANGE","DOLLAR","WILD","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","BELL","BELL","BELL","PLUM","GRAPES","DOLLAR","PLUM","DOLLAR","PLUM","ORANGE","DOLLAR","ORANGE","PLUM","PLUM","BELL","ORANGE","DOLLAR","CHERRY","DOLLAR","DOLLAR","PLUM","ORANGE","DOLLAR","BELL","CHERRY","DOLLAR","GRAPES","DOLLAR","PLUM","DOLLAR","BELL","BELL","DOLLAR","BELL","PLUM","ORANGE","DOLLAR","PLUM","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","MELON","PLUM","GRAPES","DOLLAR","BELL","ORANGE","BELL","GRAPES","CHERRY","DOLLAR","BELL","BELL","MELON","CHERRY","PLUM","PLUM","ORANGE","PLUM","MELON","BELL","BELL","PLUM","DOLLAR","PLUM","DOLLAR","CHERRY","DOLLAR","GRAPES","PLUM","BELL","DOLLAR","DOLLAR","ORANGE","PLUM","DOLLAR","CHERRY","PLUM","CHERRY","PLUM","CHERRY","WILD","ORANGE","DOLLAR","PLUM","PLUM","GRAPES","DOLLAR","CHERRY","DOLLAR","CHERRY","MELON","ORANGE","ORANGE","BELL","GRAPES","DOLLAR","PLUM","BELL","ORANGE","GRAPES","BELL","GRAPES","PLUM","ORANGE","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","BELL","PLUM","PLUM","CHERRY","ORANGE","BELL","GRAPES","PLUM","DOLLAR","DOLLAR","MELON","GRAPES","CHERRY","CHERRY","WILD","GRAPES","GRAPES","BELL","BELL","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","DOLLAR","BELL","GRAPES","DOLLAR","PLUM","ORANGE","BELL","ORANGE","BELL","PLUM","ORANGE","BELL","BELL","BELL","DOLLAR","ORANGE","ORANGE","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR","PLUM","BELL","CHERRY","DOLLAR","BELL","WILD","BELL","PLUM","GRAPES","DOLLAR","BELL","DOLLAR","DOLLAR","DOLLAR","PLUM","BELL","DOLLAR","DOLLAR","WILD","DOLLAR","PLUM","GRAPES","DOLLAR","BELL","PLUM","MELON","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","MELON","DOLLAR","PLUM","DOLLAR","ORANGE","DOLLAR","ORANGE","PLUM","DOLLAR","GRAPES","WILD","ORANGE","PLUM","WILD","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","WILD","ORANGE","CHERRY","BELL","BELL","GRAPES","PLUM","CHERRY","PLUM","CHERRY","ORANGE","PLUM","ORANGE","DOLLAR","DOLLAR","PLUM","CHERRY","CHERRY","GRAPES","BELL","PLUM","DOLLAR","CHERRY","DOLLAR","PLUM","PLUM","PLUM","ORANGE","CHERRY","PLUM","MELON","DOLLAR","DOLLAR","PLUM","ORANGE","PLUM","DOLLAR","PLUM","BELL","BELL","GRAPES","BELL","DOLLAR","BELL","ORANGE","PLUM","MELON","CHERRY","CHERRY","BELL","PLUM","DOLLAR","PLUM","PLUM","ORANGE","DOLLAR","DOLLAR","GRAPES","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","MELON","PLUM","CHERRY","BELL","MELON","GRAPES","CHERRY","CHERRY","PLUM","PLUM","DOLLAR","DOLLAR","GRAPES","BELL","PLUM","GRAPES","GRAPES","DOLLAR","ORANGE","BELL","WILD","PLUM","PLUM","CHERRY","GRAPES","PLUM","BELL","PLUM","DOLLAR","GRAPES","BELL","GRAPES","MELON","BELL","DOLLAR","DOLLAR","PLUM","PLUM","ORANGE","PLUM","BELL","DOLLAR","ORANGE","DOLLAR","BELL","DOLLAR","GRAPES","BELL","WILD","MELON","CHERRY","PLUM","ORANGE","GRAPES","BELL","ORANGE","GRAPES","PLUM","GRAPES","DOLLAR","GRAPES","PLUM","GRAPES","DOLLAR","PLUM","BELL","GRAPES","DOLLAR","MELON","BELL","ORANGE","PLUM","ORANGE","PLUM","MELON","BELL","CHERRY","BELL","DOLLAR","BELL","BELL","ORANGE","PLUM","DOLLAR","ORANGE","ORANGE","DOLLAR","CHERRY","BELL","ORANGE","ORANGE","BELL","DOLLAR","PLUM","CHERRY","CHERRY","DOLLAR","GRAPES","DOLLAR","PLUM","ORANGE","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","MELON","GRAPES","ORANGE","BELL","DOLLAR","DOLLAR","DOLLAR","PLUM","MELON","CHERRY","DOLLAR","DOLLAR","BELL","PLUM","BELL","CHERRY","BELL","MELON","DOLLAR","DOLLAR","GRAPES","GRAPES","DOLLAR","MELON","GRAPES","CHERRY","GRAPES","BELL","ORANGE","PLUM","BELL","DOLLAR","BELL","DOLLAR","PLUM","PLUM","DOLLAR","WILD","ORANGE","ORANGE","GRAPES","CHERRY","ORANGE","CHERRY","DOLLAR","DOLLAR","GRAPES","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","BELL","PLUM","MELON","BELL","ORANGE","BELL","DOLLAR","BELL","PLUM","DOLLAR","ORANGE","GRAPES","BELL","GRAPES","DOLLAR","DOLLAR","DOLLAR","DOLLAR","BELL","DOLLAR","MELON","PLUM","MELON","ORANGE","ORANGE","GRAPES","PLUM","PLUM","CHERRY","CHERRY","CHERRY","PLUM","PLUM","CHERRY","DOLLAR","BELL","CHERRY","ORANGE","PLUM","ORANGE","DOLLAR","ORANGE","DOLLAR","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","WILD","PLUM","BELL","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","PLUM","GRAPES","BELL","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","MELON","DOLLAR","GRAPES","DOLLAR","PLUM","PLUM","PLUM","ORANGE","PLUM","DOLLAR","DOLLAR","BELL","DOLLAR","PLUM","MELON","ORANGE","GRAPES","CHERRY","MELON","BELL","DOLLAR","DOLLAR","DOLLAR","BELL","CHERRY","DOLLAR","MELON","ORANGE","DOLLAR","PLUM","BELL","BELL","DOLLAR","DOLLAR","GRAPES","ORANGE","PLUM","ORANGE","DOLLAR","CHERRY","GRAPES","DOLLAR","DOLLAR","DOLLAR","PLUM","MELON","PLUM","DOLLAR","GRAPES","ORANGE","BELL","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","GRAPES","BELL","DOLLAR","WILD","BELL","DOLLAR","DOLLAR","PLUM","CHERRY","ORANGE","PLUM","MELON","DOLLAR","DOLLAR","ORANGE","BELL","ORANGE","BELL","GRAPES","DOLLAR","BELL","BELL","BELL","MELON","DOLLAR","PLUM","BELL","WILD","PLUM","ORANGE","DOLLAR","CHERRY","ORANGE","PLUM","PLUM","DOLLAR","BELL","DOLLAR","GRAPES","PLUM","PLUM","CHERRY","ORANGE","DOLLAR","ORANGE","BELL","ORANGE","ORANGE","PLUM","DOLLAR","PLUM","WILD","DOLLAR","PLUM","CHERRY","WILD","DOLLAR","DOLLAR","WILD","ORANGE","MELON","MELON","DOLLAR","PLUM","DOLLAR","BELL","ORANGE","ORANGE","DOLLAR","BELL","PLUM","DOLLAR","GRAPES","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","BELL","MELON","DOLLAR","DOLLAR","GRAPES","ORANGE","ORANGE","BELL","PLUM","BELL","CHERRY","DOLLAR","DOLLAR","DOLLAR","BELL","PLUM","DOLLAR","DOLLAR","DOLLAR","WILD","CHERRY","PLUM","ORANGE","DOLLAR","BELL","DOLLAR","BELL","DOLLAR","DOLLAR","PLUM","DOLLAR","WILD","PLUM","PLUM","DOLLAR","ORANGE","DOLLAR","GRAPES","ORANGE","BELL","DOLLAR","DOLLAR","MELON","MELON","ORANGE","DOLLAR","PLUM","PLUM","PLUM","ORANGE","DOLLAR","PLUM","DOLLAR","DOLLAR","BELL","BELL","ORANGE","MELON","GRAPES","BELL","CHERRY","MELON","BELL","BELL","PLUM","ORANGE","MELON","GRAPES","DOLLAR","GRAPES","BELL","GRAPES","DOLLAR","PLUM","BELL","DOLLAR","PLUM","ORANGE","DOLLAR","BELL","ORANGE","PLUM","MELON","PLUM","DOLLAR","PLUM","DOLLAR","GRAPES","MELON","DOLLAR","WILD","PLUM","MELON","BELL","ORANGE","BELL","DOLLAR","DOLLAR","GRAPES","DOLLAR","BELL","DOLLAR","GRAPES","CHERRY","DOLLAR","PLUM","MELON","DOLLAR","PLUM","GRAPES","PLUM","PLUM","CHERRY","GRAPES","CHERRY","PLUM","PLUM","BELL","PLUM","MELON","ORANGE","PLUM","ORANGE","BELL","GRAPES","GRAPES","ORANGE","GRAPES","GRAPES","DOLLAR","ORANGE","ORANGE","MELON","BELL","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","BELL","DOLLAR","MELON","DOLLAR","CHERRY","ORANGE","MELON","PLUM","BELL","ORANGE","GRAPES","BELL","MELON","GRAPES","DOLLAR","MELON","DOLLAR","DOLLAR","ORANGE","PLUM","BELL","DOLLAR","PLUM","DOLLAR","GRAPES","DOLLAR","CHERRY","BELL","PLUM","ORANGE","DOLLAR","BELL","BELL","PLUM","PLUM","DOLLAR","DOLLAR","CHERRY","GRAPES","DOLLAR","CHERRY","MELON","DOLLAR","PLUM","WILD","DOLLAR","ORANGE","PLUM","PLUM","DOLLAR","PLUM","PLUM","BELL","BELL","MELON","PLUM","ORANGE","DOLLAR","PLUM","BELL","DOLLAR","MELON","DOLLAR"],["BELL","CHERRY","GRAPES","PLUM","BELL","SEVEN","GRAPES","CHERRY","PLUM","BELL","BELL","PLUM","CHERRY","CHERRY","ORANGE","BELL","PLUM","GRAPES","PLUM","SEVEN","SEVEN","BELL","BELL","PLUM","CHERRY","SEVEN","BELL","PLUM","ORANGE","CHERRY","ORANGE","CHERRY","ORANGE","SEVEN","CHERRY","PLUM","DOLLAR","CHERRY","PLUM","PLUM","PLUM","PLUM","CHERRY","PLUM","ORANGE","PLUM","PLUM","ORANGE","PLUM","PLUM","GRAPES","CHERRY","PLUM","SEVEN","PLUM","SEVEN","BELL","BELL","ORANGE","PLUM","PLUM","PLUM","CHERRY","PLUM","ORANGE","PLUM","BELL","CHERRY","ORANGE","PLUM","CHERRY","PLUM","CHERRY","BELL","BELL","CHERRY","CHERRY","PLUM","CHERRY","BELL","SEVEN","BELL","PLUM","PLUM","PLUM","CHERRY","SEVEN","CHERRY","BELL","CHERRY","SEVEN","BELL","PLUM","PLUM","CHERRY","CHERRY","PLUM","BELL","PLUM","BELL","PLUM","CHERRY","BELL","PLUM","PLUM","WILD","PLUM","BELL","CHERRY","SEVEN","PLUM","CHERRY","CHERRY","BELL","GRAPES","SEVEN","PLUM","PLUM","PLUM","BELL","PLUM","CHERRY","PLUM","CHERRY","PLUM","PLUM","BELL","CHERRY","ORANGE","PLUM","SEVEN","PLUM","CHERRY","BELL","PLUM","CHERRY","ORANGE","CHERRY","PLUM","PLUM","GRAPES","CHERRY","SEVEN","GRAPES","SEVEN","BELL","PLUM","SEVEN","CHERRY","CHERRY","BELL","CHERRY","CHERRY","PLUM","CHERRY","BELL","CHERRY","CHERRY","SEVEN","BELL","SEVEN","BELL","CHERRY","CHERRY","CHERRY","CHERRY","PLUM","CHERRY","PLUM","BELL","SEVEN","ORANGE","CHERRY","PLUM","SEVEN","GRAPES","CHERRY","ORANGE","BELL","PLUM","BELL","PLUM","CHERRY","CHERRY","CHERRY","CHERRY","PLUM","ORANGE","PLUM","CHERRY","PLUM","BELL","BELL","PLUM","CHERRY","SEVEN","PLUM","BELL","CHERRY","BELL","BELL","CHERRY","BELL","BELL","CHERRY","CHERRY","PLUM","PLUM","SEVEN","CHERRY","PLUM","BELL","CHERRY","PLUM","PLUM","CHERRY","CHERRY","BELL","BELL","CHERRY","ORANGE","PLUM","PLUM","CHERRY","SEVEN","PLUM","PLUM","PLUM","PLUM","BELL","CHERRY","CHERRY","CHERRY","PLUM","BELL","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","PLUM","PLUM","PLUM","CHERRY","SEVEN","PLUM","CHERRY","ORANGE","CHERRY","BELL","CHERRY","CHERRY","BELL","PLUM","PLUM","SEVEN","PLUM","PLUM","BELL","CHERRY","CHERRY","PLUM","CHERRY","PLUM","PLUM","BELL","PLUM","PLUM","PLUM","PLUM","BELL","SEVEN","SEVEN","CHERRY","CHERRY","CHERRY","PLUM","BELL","BELL","CHERRY","CHERRY","BELL","CHERRY","CHERRY","PLUM","CHERRY","CHERRY","CHERRY","ORANGE","BELL","BELL","SEVEN","SEVEN","PLUM","PLUM","PLUM","PLUM","BELL","PLUM","CHERRY","BELL","BELL","PLUM","PLUM","PLUM","CHERRY","BELL","GRAPES","CHERRY","BELL","PLUM","PLUM","BELL","BELL","BELL","BELL","PLUM","BELL","CHERRY","BELL","PLUM","ORANGE","CHERRY","PLUM","ORANGE","PLUM","CHERRY","PLUM","CHERRY","CHERRY","BELL","PLUM","BELL","BELL","BELL","PLUM","PLUM","CHERRY","PLUM","PLUM","CHERRY","SEVEN","CHERRY","BELL","PLUM","PLUM","CHERRY","PLUM","PLUM","CHERRY","PLUM","PLUM","BELL","CHERRY","BELL","PLUM","PLUM","PLUM","PLUM","CHERRY","BELL","PLUM","PLUM","PLUM","SEVEN","PLUM","BELL","BELL","GRAPES","CHERRY","PLUM","PLUM","PLUM","PLUM","BELL","CHERRY","PLUM","GRAPES","PLUM","GRAPES","CHERRY","ORANGE","PLUM","BELL","BELL","PLUM","BELL","CHERRY","PLUM","CHERRY","BELL","PLUM","CHERRY","PLUM","CHERRY","BELL","CHERRY","PLUM","BELL","BELL","PLUM","CHERRY","PLUM","PLUM","ORANGE","PLUM","PLUM","BELL","BELL","CHERRY","PLUM","PLUM","CHERRY","CHERRY","BELL","CHERRY","CHERRY","PLUM","PLUM","PLUM","PLUM","SEVEN","CHERRY","CHERRY","BELL","CHERRY","ORANGE","PLUM","BELL","CHERRY","CHERRY","CHERRY","PLUM","SEVEN","CHERRY","ORANGE","SEVEN","PLUM","CHERRY","PLUM","SEVEN","CHERRY","CHERRY","SEVEN","ORANGE","BELL","CHERRY","BELL","MELON","CHERRY","CHERRY","PLUM","SEVEN","CHERRY","PLUM","ORANGE","BELL","CHERRY","CHERRY","PLUM","CHERRY","PLUM","CHERRY","BELL","BELL","GRAPES","BELL","CHERRY","CHERRY","BELL","PLUM","ORANGE","PLUM","SEVEN","BELL","ORANGE","PLUM","CHERRY","CHERRY","PLUM","CHERRY","PLUM","BELL","BELL","CHERRY","ORANGE","BELL","GRAPES","SEVEN","SEVEN","PLUM","CHERRY","PLUM","BELL","BELL","BELL","PLUM","PLUM","BELL","PLUM","CHERRY","PLUM","PLUM","CHERRY","PLUM","CHERRY","CHERRY","PLUM","PLUM","CHERRY","BELL","CHERRY","CHERRY","CHERRY","PLUM","PLUM","PLUM","GRAPES","PLUM","BELL","BELL","CHERRY","BELL","PLUM","PLUM","SEVEN","PLUM","CHERRY","CHERRY","CHERRY","ORANGE","BELL","PLUM","GRAPES","SEVEN","ORANGE","PLUM","PLUM","PLUM","PLUM","BELL","CHERRY","CHERRY","BELL","CHERRY","PLUM","SEVEN","PLUM","PLUM","BELL","CHERRY","PLUM","CHERRY","BELL","CHERRY","GRAPES","BELL","BELL","PLUM","CHERRY","CHERRY","PLUM","BELL","PLUM","SEVEN","BELL","BELL","BELL","PLUM","BELL","CHERRY","CHERRY","BELL","BELL","CHERRY","ORANGE","PLUM","CHERRY","CHERRY","PLUM","SEVEN","BELL","CHERRY","PLUM","ORANGE","PLUM","BELL","SEVEN","CHERRY","PLUM","BELL","ORANGE","BELL","PLUM","CHERRY","CHERRY","CHERRY","BELL","SEVEN","BELL","CHERRY","CHERRY","PLUM","BELL","SEVEN","PLUM","BELL","CHERRY","PLUM","PLUM","CHERRY","PLUM","SEVEN","CHERRY","CHERRY","CHERRY","CHERRY","PLUM","PLUM","BELL","GRAPES","PLUM","CHERRY","BELL","CHERRY","BELL","PLUM","PLUM","ORANGE","SEVEN","PLUM","BELL","PLUM","PLUM","SEVEN","PLUM","SEVEN","SEVEN","PLUM","PLUM","CHERRY","CHERRY","BELL","BELL","GRAPES","CHERRY","BELL","PLUM","CHERRY","CHERRY","CHERRY","PLUM","SEVEN","CHERRY","PLUM","CHERRY","CHERRY","BELL","ORANGE","CHERRY","BELL","ORANGE","SEVEN","BELL","SEVEN","ORANGE","PLUM","PLUM","BELL","CHERRY","GRAPES","CHERRY","PLUM","PLUM","PLUM","CHERRY","BELL","CHERRY","PLUM","PLUM","SEVEN","BELL","PLUM","CHERRY","CHERRY","PLUM","GRAPES","PLUM","CHERRY","CHERRY","BELL","PLUM","CHERRY","GRAPES","PLUM","ORANGE","PLUM","PLUM","CHERRY","PLUM","BELL","GRAPES","ORANGE","CHERRY","CHERRY","BELL","CHERRY","CHERRY","PLUM","PLUM","CHERRY","SEVEN","PLUM","BELL","PLUM","SEVEN","PLUM","BELL","GRAPES","PLUM","BELL","CHERRY","CHERRY","BELL","PLUM","BELL","SEVEN","BELL","PLUM","CHERRY","CHERRY","SEVEN","BELL","BELL","ORANGE","BELL","CHERRY","CHERRY","BELL","PLUM","BELL","CHERRY","BELL","BELL","BELL","SEVEN","CHERRY","CHERRY","PLUM","PLUM","PLUM","BELL","PLUM","DOLLAR","BELL","BELL","BELL","BELL","CHERRY","CHERRY","ORANGE","SEVEN","PLUM","BELL","PLUM","CHERRY","PLUM","SEVEN","BELL","PLUM","PLUM","PLUM","BELL","CHERRY","BELL","PLUM","ORANGE","PLUM","GRAPES","PLUM","SEVEN","PLUM","PLUM","BELL","PLUM","PLUM","CHERRY","CHERRY","BELL","CHERRY","PLUM","PLUM","BELL","PLUM","CHERRY","CHERRY","PLUM","ORANGE","PLUM","CHERRY","SEVEN","CHERRY","ORANGE","PLUM","CHERRY","SEVEN","BELL","PLUM","CHERRY","PLUM","CHERRY","CHERRY","CHERRY","PLUM","PLUM","PLUM","PLUM","PLUM","BELL","BELL","CHERRY","PLUM","PLUM","PLUM","CHERRY","CHERRY","PLUM","CHERRY","PLUM","ORANGE","SEVEN","PLUM","CHERRY","PLUM","CHERRY","BELL","CHERRY","CHERRY","PLUM","PLUM","BELL","CHERRY","SEVEN","PLUM","PLUM","PLUM","PLUM","BELL","PLUM","CHERRY","PLUM","PLUM","PLUM","PLUM","PLUM","PLUM","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","PLUM","PLUM","BELL","BELL","CHERRY","ORANGE","BELL","SEVEN","PLUM","PLUM","GRAPES","DOLLAR","SEVEN","BELL","BELL","CHERRY","PLUM","PLUM","ORANGE","BELL","ORANGE","CHERRY","DOLLAR","BELL","PLUM","BELL","SEVEN","BELL","CHERRY","CHERRY","BELL","PLUM","CHERRY","CHERRY","PLUM","CHERRY","CHERRY","PLUM","PLUM","PLUM","SEVEN","CHERRY","CHERRY","PLUM","CHERRY","CHERRY","SEVEN","ORANGE","CHERRY","SEVEN","ORANGE","PLUM","ORANGE","PLUM","BELL","ORANGE","GRAPES","SEVEN","CHERRY","ORANGE","CHERRY","PLUM","PLUM","SEVEN","PLUM","CHERRY","ORANGE","PLUM","BELL","BELL","SEVEN","BELL","BELL","CHERRY","PLUM","CHERRY","CHERRY","BELL","CHERRY","PLUM","BELL","GRAPES","CHERRY","BELL","BELL","CHERRY","SEVEN","PLUM","CHERRY","PLUM","CHERRY","BELL","PLUM","BELL","BELL","PLUM","SEVEN","BELL","SEVEN","SEVEN","PLUM","PLUM","CHERRY","PLUM","BELL","BELL","PLUM","BELL","CHERRY","SEVEN","BELL","ORANGE","CHERRY","GRAPES","BELL","CHERRY","SEVEN","SEVEN","BELL","CHERRY","CHERRY","CHERRY","SEVEN","ORANGE","BELL","CHERRY","SEVEN","ORANGE","CHERRY","BELL","BELL","PLUM","PLUM","SEVEN","CHERRY","GRAPES","PLUM"],["ORANGE","CHERRY","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","CHERRY","CHERRY","DOLLAR","PLUM","CHERRY","ORANGE","DOLLAR","SEVEN","DOLLAR","DOLLAR","DOLLAR","DOLLAR","SEVEN","DOLLAR","CHERRY","ORANGE","CHERRY","DOLLAR","ORANGE","ORANGE","ORANGE","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","ORANGE","ORANGE","ORANGE","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","ORANGE","CHERRY","ORANGE","SEVEN","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","CHERRY","ORANGE","SEVEN","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","CHERRY","CHERRY","DOLLAR","ORANGE","CHERRY","ORANGE","CHERRY","CHERRY","ORANGE","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","CHERRY","ORANGE","DOLLAR","ORANGE","SEVEN","SEVEN","CHERRY","CHERRY","ORANGE","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","ORANGE","DOLLAR","ORANGE","ORANGE","ORANGE","ORANGE","ORANGE","ORANGE","BELL","ORANGE","DOLLAR","BELL","DOLLAR","CHERRY","ORANGE","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","DOLLAR","SEVEN","DOLLAR","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","DOLLAR","ORANGE","ORANGE","CHERRY","ORANGE","ORANGE","ORANGE","ORANGE","ORANGE","SEVEN","ORANGE","SEVEN","DOLLAR","CHERRY","CHERRY","ORANGE","ORANGE","DOLLAR","PLUM","ORANGE","ORANGE","DOLLAR","SEVEN","ORANGE","CHERRY","DOLLAR","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","ORANGE","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","ORANGE","ORANGE","DOLLAR","ORANGE","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","CHERRY","CHERRY","CHERRY","DOLLAR","DOLLAR","ORANGE","SEVEN","DOLLAR","DOLLAR","SEVEN","DOLLAR","DOLLAR","DOLLAR","CHERRY","SEVEN","DOLLAR","DOLLAR","CHERRY","PLUM","BELL","CHERRY","PLUM","SEVEN","CHERRY","CHERRY","DOLLAR","ORANGE","DOLLAR","PLUM","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","CHERRY","CHERRY","ORANGE","ORANGE","PLUM","DOLLAR","ORANGE","CHERRY","DOLLAR","DOLLAR","PLUM","DOLLAR","CHERRY","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","CHERRY","CHERRY","ORANGE","CHERRY","ORANGE","DOLLAR","CHERRY","DOLLAR","DOLLAR","ORANGE","CHERRY","ORANGE","ORANGE","ORANGE","CHERRY","ORANGE","ORANGE","ORANGE","SEVEN","ORANGE","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","DOLLAR","ORANGE","ORANGE","DOLLAR","ORANGE","DOLLAR","ORANGE","ORANGE","ORANGE","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","ORANGE","PLUM","ORANGE","DOLLAR","DOLLAR","PLUM","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","DOLLAR","ORANGE","ORANGE","CHERRY","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","ORANGE","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","ORANGE","CHERRY","ORANGE","DOLLAR","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","DOLLAR","ORANGE","SEVEN","DOLLAR","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","SEVEN","CHERRY","PLUM","DOLLAR","ORANGE","CHERRY","ORANGE","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","CHERRY","ORANGE","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","ORANGE","DOLLAR","ORANGE","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","DOLLAR","CHERRY","ORANGE","ORANGE","SEVEN","DOLLAR","DOLLAR","SEVEN","CHERRY","DOLLAR","ORANGE","DOLLAR","ORANGE","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","SEVEN","ORANGE","ORANGE","CHERRY","DOLLAR","CHERRY","CHERRY","ORANGE","DOLLAR","CHERRY","ORANGE","SEVEN","SEVEN","DOLLAR","CHERRY","ORANGE","DOLLAR","CHERRY","ORANGE","SEVEN","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","SEVEN","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","ORANGE","ORANGE","CHERRY","CHERRY","ORANGE","SEVEN","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","SEVEN","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","ORANGE","ORANGE","DOLLAR","ORANGE","DOLLAR","PLUM","DOLLAR","ORANGE","ORANGE","SEVEN","DOLLAR","DOLLAR","ORANGE","ORANGE","ORANGE","DOLLAR","SEVEN","DOLLAR","CHERRY","ORANGE","ORANGE","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","CHERRY","ORANGE","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","ORANGE","BELL","ORANGE","CHERRY","ORANGE","DOLLAR","ORANGE","SEVEN","ORANGE","SEVEN","ORANGE","SEVEN","CHERRY","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","BELL","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","ORANGE","ORANGE","DOLLAR","CHERRY","PLUM","CHERRY","CHERRY","SEVEN","CHERRY","CHERRY","CHERRY","CHERRY","DOLLAR","SEVEN","DOLLAR","DOLLAR","CHERRY","ORANGE","CHERRY","DOLLAR","CHERRY","CHERRY","DOLLAR","PLUM","ORANGE","ORANGE","CHERRY","ORANGE","ORANGE","ORANGE","BELL","ORANGE","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","ORANGE","DOLLAR","DOLLAR","SEVEN","ORANGE","CHERRY","DOLLAR","DOLLAR","DOLLAR","ORANGE","ORANGE","CHERRY","SEVEN","DOLLAR","DOLLAR","SEVEN","ORANGE","ORANGE","DOLLAR","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","ORANGE","PLUM","DOLLAR","DOLLAR","ORANGE","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","SEVEN","ORANGE","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","DOLLAR","CHERRY","ORANGE","DOLLAR","SEVEN","CHERRY","DOLLAR","ORANGE","DOLLAR","DOLLAR","SEVEN","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","DOLLAR","ORANGE","ORANGE","CHERRY","ORANGE","DOLLAR","ORANGE","DOLLAR","CHERRY","PLUM","ORANGE","DOLLAR","DOLLAR","ORANGE","DOLLAR","ORANGE","SEVEN","CHERRY","SEVEN","CHERRY","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","SEVEN","ORANGE","DOLLAR","ORANGE","DOLLAR","CHERRY","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","CHERRY","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","ORANGE","CHERRY","CHERRY","CHERRY","ORANGE","ORANGE","ORANGE","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","ORANGE","ORANGE","ORANGE","DOLLAR","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","CHERRY","ORANGE","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","CHERRY","SEVEN","CHERRY","SEVEN","DOLLAR","ORANGE","CHERRY","CHERRY","ORANGE","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","CHERRY","ORANGE","PLUM","DOLLAR","CHERRY","CHERRY","ORANGE","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","SEVEN","ORANGE","PLUM","ORANGE","DOLLAR","DOLLAR","DOLLAR","CHERRY","ORANGE","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","ORANGE","SEVEN","CHERRY","PLUM","DOLLAR","ORANGE","BELL","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","ORANGE","DOLLAR","CHERRY","DOLLAR","CHERRY","CHERRY","CHERRY","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","CHERRY","CHERRY","ORANGE","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","ORANGE","ORANGE","CHERRY","CHERRY","DOLLAR","SEVEN","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","ORANGE","CHERRY","CHERRY","DOLLAR","CHERRY","CHERRY","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","SEVEN","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","ORANGE","DOLLAR","ORANGE","CHERRY","CHERRY","CHERRY","DOLLAR","ORANGE","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","CHERRY","ORANGE","ORANGE","DOLLAR","DOLLAR","CHERRY","SEVEN","DOLLAR","CHERRY","CHERRY","DOLLAR","ORANGE","CHERRY","DOLLAR","ORANGE","DOLLAR","CHERRY","PLUM","CHERRY","DOLLAR","ORANGE","SEVEN","DOLLAR","CHERRY","SEVEN","ORANGE","ORANGE","ORANGE","ORANGE","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","DOLLAR","ORANGE","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","SEVEN","DOLLAR","ORANGE","CHERRY","DOLLAR","SEVEN","CHERRY","CHERRY","DOLLAR","CHERRY","ORANGE","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","PLUM","ORANGE","ORANGE","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","ORANGE","ORANGE","SEVEN","CHERRY","ORANGE","CHERRY","CHERRY","ORANGE","ORANGE","SEVEN","ORANGE","ORANGE","DOLLAR","BELL","CHERRY","DOLLAR","CHERRY","PLUM","ORANGE","CHERRY","ORANGE","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","ORANGE","ORANGE","DOLLAR","SEVEN","DOLLAR","DOLLAR","SEVEN","DOLLAR","CHERRY","CHERRY","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","PLUM","BELL","ORANGE"],["DOLLAR","DOLLAR","PLUM","PLUM","CHERRY","CHERRY","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","PLUM","CHERRY","PLUM","PLUM","DOLLAR","PLUM","PLUM","CHERRY","PLUM","PLUM","PLUM","PLUM","ORANGE","CHERRY","PLUM","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","PLUM","PLUM","PLUM","PLUM","CHERRY","DOLLAR","ORANGE","CHERRY","ORANGE","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","ORANGE","DOLLAR","PLUM","PLUM","CHERRY","PLUM","CHERRY","DOLLAR","DOLLAR","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","BELL","PLUM","PLUM","DOLLAR","BELL","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR","ORANGE","PLUM","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","ORANGE","BELL","PLUM","PLUM","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","CHERRY","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","CHERRY","CHERRY","ORANGE","PLUM","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","CHERRY","PLUM","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","ORANGE","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","BELL","CHERRY","DOLLAR","DOLLAR","PLUM","ORANGE","DOLLAR","DOLLAR","CHERRY","PLUM","BELL","DOLLAR","PLUM","DOLLAR","PLUM","ORANGE","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","ORANGE","DOLLAR","PLUM","CHERRY","PLUM","DOLLAR","PLUM","PLUM","ORANGE","BELL","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","ORANGE","CHERRY","PLUM","CHERRY","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","ORANGE","CHERRY","PLUM","PLUM","ORANGE","DOLLAR","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","PLUM","CHERRY","CHERRY","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","ORANGE","PLUM","BELL","PLUM","PLUM","CHERRY","PLUM","PLUM","PLUM","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","CHERRY","DOLLAR","PLUM","CHERRY","PLUM","CHERRY","DOLLAR","CHERRY","CHERRY","PLUM","PLUM","ORANGE","DOLLAR","PLUM","CHERRY","PLUM","CHERRY","DOLLAR","DOLLAR","CHERRY","CHERRY","ORANGE","BELL","DOLLAR","DOLLAR","ORANGE","DOLLAR","DOLLAR","CHERRY","CHERRY","DOLLAR","PLUM","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","DOLLAR","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","CHERRY","CHERRY","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","ORANGE","PLUM","DOLLAR","CHERRY","PLUM","DOLLAR","CHERRY","ORANGE","PLUM","ORANGE","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","PLUM","PLUM","DOLLAR","BELL","DOLLAR","ORANGE","PLUM","CHERRY","DOLLAR","ORANGE","DOLLAR","PLUM","BELL","PLUM","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","CHERRY","PLUM","DOLLAR","ORANGE","BELL","CHERRY","CHERRY","PLUM","PLUM","PLUM","PLUM","BELL","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","CHERRY","PLUM","DOLLAR","ORANGE","PLUM","CHERRY","DOLLAR","ORANGE","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","PLUM","PLUM","PLUM","CHERRY","DOLLAR","PLUM","CHERRY","PLUM","DOLLAR","DOLLAR","CHERRY","BELL","DOLLAR","PLUM","ORANGE","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","CHERRY","DOLLAR","ORANGE","DOLLAR","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","PLUM","DOLLAR","PLUM","PLUM","CHERRY","CHERRY","DOLLAR","CHERRY","PLUM","PLUM","DOLLAR","DOLLAR","DOLLAR","ORANGE","PLUM","CHERRY","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","PLUM","PLUM","BELL","PLUM","DOLLAR","DOLLAR","CHERRY","CHERRY","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","PLUM","PLUM","PLUM","ORANGE","CHERRY","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","ORANGE","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","ORANGE","CHERRY","DOLLAR","PLUM","BELL","PLUM","PLUM","PLUM","PLUM","PLUM","CHERRY","CHERRY","CHERRY","BELL","DOLLAR","PLUM","CHERRY","BELL","PLUM","CHERRY","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","PLUM","ORANGE","PLUM","DOLLAR","ORANGE","DOLLAR","DOLLAR","ORANGE","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","ORANGE","PLUM","PLUM","PLUM","PLUM","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","PLUM","PLUM","CHERRY","DOLLAR","CHERRY","DOLLAR","PLUM","DOLLAR","ORANGE","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","ORANGE","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","CHERRY","PLUM","PLUM","PLUM","PLUM","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","PLUM","CHERRY","DOLLAR","CHERRY","PLUM","PLUM","PLUM","DOLLAR","DOLLAR","DOLLAR","ORANGE","BELL","CHERRY","DOLLAR","DOLLAR","PLUM","PLUM","CHERRY","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","PLUM","DOLLAR","PLUM","PLUM","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","PLUM","BELL","PLUM","DOLLAR","DOLLAR","PLUM","CHERRY","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","PLUM","PLUM","DOLLAR","CHERRY","CHERRY","DOLLAR","PLUM","CHERRY","PLUM","BELL","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","ORANGE","CHERRY","ORANGE","DOLLAR","CHERRY","BELL","PLUM","BELL","DOLLAR","PLUM","DOLLAR","PLUM","CHERRY","CHERRY","DOLLAR","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","CHERRY","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","CHERRY","PLUM","PLUM","CHERRY","DOLLAR","CHERRY","CHERRY","PLUM","ORANGE","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","PLUM","CHERRY","CHERRY","CHERRY","CHERRY","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","ORANGE","PLUM","ORANGE","PLUM","CHERRY","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","DOLLAR","CHERRY","PLUM","PLUM","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","ORANGE","CHERRY","PLUM","ORANGE","PLUM","PLUM","CHERRY","DOLLAR","PLUM","BELL","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","ORANGE","PLUM","DOLLAR","PLUM","ORANGE","CHERRY","DOLLAR","DOLLAR","PLUM","DOLLAR","CHERRY","DOLLAR","PLUM","DOLLAR","CHERRY","PLUM","PLUM","ORANGE","PLUM","DOLLAR","PLUM","DOLLAR","DOLLAR","CHERRY","DOLLAR","BELL","DOLLAR","DOLLAR","ORANGE","DOLLAR","CHERRY","CHERRY","PLUM","PLUM","CHERRY","PLUM","CHERRY","PLUM","DOLLAR","ORANGE","DOLLAR","CHERRY","ORANGE","BELL","PLUM","PLUM","DOLLAR","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","PLUM","CHERRY","ORANGE","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","DOLLAR","BELL","PLUM","DOLLAR","CHERRY","DOLLAR","ORANGE","PLUM","PLUM","ORANGE","PLUM","CHERRY","CHERRY","DOLLAR","BELL","DOLLAR","CHERRY","DOLLAR","ORANGE","PLUM","CHERRY","CHERRY","PLUM","PLUM","CHERRY","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","PLUM","PLUM","DOLLAR","PLUM","CHERRY","ORANGE","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","PLUM","CHERRY","CHERRY","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","CHERRY","DOLLAR","ORANGE","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","CHERRY","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","PLUM","DOLLAR","DOLLAR","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","ORANGE","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","CHERRY","CHERRY","PLUM","DOLLAR","DOLLAR","DOLLAR","DOLLAR","PLUM","DOLLAR","ORANGE","DOLLAR","DOLLAR","PLUM","BELL","PLUM","DOLLAR","DOLLAR","CHERRY","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","PLUM","PLUM","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","DOLLAR","DOLLAR","DOLLAR","CHERRY","CHERRY","PLUM","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","PLUM","PLUM","DOLLAR","PLUM","PLUM","DOLLAR","CHERRY","DOLLAR","DOLLAR","CHERRY","PLUM","ORANGE","DOLLAR","CHERRY","CHERRY","DOLLAR","PLUM","PLUM","DOLLAR","DOLLAR","PLUM","PLUM","DOLLAR"]];
function weightedSymbol(){
 if(isMV81()) return MV81_REEL_STRIPS[Math.floor(Math.random()*4)][Math.floor(Math.random()*18)];
 const weights=current.symbols.map(s=>Math.max(1,Math.round(100/(current.payouts[s]||1))));
 const total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total;
 for(let i=0;i<weights.length;i++){r-=weights[i];if(r<=0)return current.symbols[i]}
 return current.symbols.at(-1)
}
function outcomeMV81(){
  const out=Array(12).fill("CHERRY");
  for(let c=0;c<4;c++){
    const strip=MV81_REEL_STRIPS[c];
    const stop=Math.floor(Math.random()*strip.length);
    for(let row=0;row<3;row++) out[row*4+c]=strip[(stop+row)%strip.length];
  }
  return out;
}
function outcome(){
 const cols=+current.layout.split("x")[0],rows=+current.layout.split("x")[1];
 if(isMV81()) return outcomeMV81();
 return Array.from({length:cols*rows},()=>weightedSymbol());
}
function getCell(r,col,row,cols){return r[row*cols+col]}
function lineMatches(r,pattern,len){
 const cols=4;
 let base=null,wilds=0;
 for(let c=0;c<len;c++){
   const s=getCell(r,c,pattern[c],cols);
   if(s==="WILD"){wilds++;continue}
   if(base===null) base=s;
   else if(s!==base)return {symbol:null,wilds};
 }
 return {symbol:base,wilds};
}
function calculateMV81(r, wager=bet){
 const wins=[];
 // 3-symbol wins: exactly the 27 criss-cross paths through reels 1-3.
 for(let i=0;i<MV81_PATTERNS_3.length;i++){
   const p=MV81_PATTERNS_3[i], m=lineMatches(r,p,3);
   if(!m.symbol)continue;
   const mult=current.payouts[m.symbol]?.[3]||0;
   if(!mult)continue;
   const wildMul=m.wilds===1?2:m.wilds===2?4:m.wilds===3?8:1;
   wins.push({pattern:p,cols:3,symbol:m.symbol,count:3,wilds:m.wilds,amount:Math.round(wager*mult*wildMul*MV81_PAYOUT_FACTOR)});
 }
 // 4-symbol wins: all 81 criss-cross paths. A 4-symbol win supersedes
 // the corresponding 3-symbol path; we remove it below.
 for(let i=0;i<MV81_PATTERNS_4.length;i++){
   const p=MV81_PATTERNS_4[i], m=lineMatches(r,p,4);
   if(!m.symbol)continue;
   const mult=current.payouts[m.symbol]?.[4]||0;
   if(!mult)continue;
   const wildMul=m.wilds===1?2:m.wilds===2?4:m.wilds===3?8:1;
   wins.push({pattern:p,cols:4,symbol:m.symbol,count:4,wilds:m.wilds,amount:Math.round(wager*mult*wildMul*MV81_PAYOUT_FACTOR)});
 }
 // Only the highest win on a winning line is valid. Each 4-reel path
 // corresponds to one of the 27 three-reel paths, so suppress the 3-way
 // entry whenever its exact first-three positions also win on reel 4.
 const fourKeys=new Set(wins.filter(w=>w.cols===4).map(w=>w.pattern.slice(0,3).join("")));
 const finalWins=wins.filter(w=>w.cols===4 || !fourKeys.has(w.pattern.join("")));
 return finalWins;
}
function calculateWin(r){
 if(isMV81())return calculateMV81(r).reduce((a,w)=>a+w.amount,0);
 const cols=+current.layout.split("x")[0], rows=+current.layout.split("x")[1];
 let wins=0;
 for(let row=0;row<rows;row++){const line=r.slice(row*cols,(row+1)*cols);if(line.length===cols&&line.every(x=>x===line[0]))wins+=bet*(current.payouts[line[0]]||0)}
 return wins;
}
function clearWinFX(){
 document.querySelectorAll(".reel-win,.mv81-hit,.mv81-path").forEach(x=>x.classList.remove("reel-win","mv81-hit","mv81-path"));
 document.querySelectorAll(".mv81-line-svg").forEach(x=>x.remove());
}
function highlightMV81Wins(r,wins){
 clearWinFX();
 const frame=$("reelFrame"), rect=frame.getBoundingClientRect();
 const cols=4, rows=3;
 const cells=[...frame.querySelectorAll(".reel")];
 wins.forEach((w,wi)=>{
   w.pattern.forEach((row,c)=>{
     const idx=row*cols+c;
     cells[idx]?.classList.add("mv81-hit");
   });
 });
 // Draw each winning path as an SVG overlay.
 if(wins.length){
   const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");
   svg.classList.add("mv81-line-svg");
   svg.setAttribute("viewBox",`0 0 ${frame.clientWidth} ${frame.clientHeight}`);
   svg.setAttribute("preserveAspectRatio","none");
   wins.slice(0,12).forEach((w,wi)=>{
     const pts=w.pattern.map((row,c)=>{
       const cell=cells[row*cols+c];
       return `${cell.offsetLeft+cell.offsetWidth/2},${cell.offsetTop+cell.offsetHeight/2}`;
     }).join(" ");
     const poly=document.createElementNS("http://www.w3.org/2000/svg","polyline");
     poly.setAttribute("points",pts);poly.setAttribute("class","mv81-path");
     poly.style.animationDelay=`${wi*90}ms`;
     svg.appendChild(poly);
   });
   frame.appendChild(svg);
 }
}
function playTone(type){
 if(!sound)return;
 try{
  const C=window.AudioContext||window.webkitAudioContext;if(!C)return;
  const c=window.__mvAudio||(window.__mvAudio=new C());
  const o=c.createOscillator(),g=c.createGain();
  const now=c.currentTime;
  const f=type==="stop"?240:type==="win"?520:type==="bigwin"?760:120;
  o.type=type==="spin"?"sawtooth":"sine";o.frequency.setValueAtTime(f,now);
  if(type==="spin")o.frequency.exponentialRampToValueAtTime(220,now+.12);
  if(type==="win")o.frequency.exponentialRampToValueAtTime(900,now+.18);
  if(type==="bigwin")o.frequency.exponentialRampToValueAtTime(1200,now+.28);
  g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(type==="bigwin"?.08:.045,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+(type==="bigwin"?.34:.2));
  o.connect(g);g.connect(c.destination);o.start(now);o.stop(now+(type==="bigwin"?.36:.22));
 }catch(e){}
}
async function spin(){
 if(spinning)return;if(balance<bet){toast("NEMÁŠ DOSTATEK TOKENŮ");return}
 spinning=true;$("spinBtn").disabled=true;balance-=bet;updateBalances();$("machineResult").textContent="SPINNING...";
 clearWinFX(); playTone("spin");
 const reels=[...document.querySelectorAll(".reel")];
 let r=[];
 if(isMV81()){
   reels.forEach(el=>el.classList.add("reel-spin"));
   for(let round=0;round<20;round++){
     reels.forEach((el,i)=>el.innerHTML=symbolMarkup(MV81_REEL_STRIPS[i%4][Math.floor(Math.random()*18)]));
     await new Promise(r=>setTimeout(r,45+round*2));
   }
   r=outcome();setReels(r);
   for(let i=0;i<4;i++){await new Promise(r=>setTimeout(r,150)); playTone("stop");}
   reels.forEach(el=>el.classList.remove("reel-spin"));
   const wins=calculateMV81(r),win=Math.min(100*bet,wins.reduce((a,w)=>a+w.amount,0));
   if(win){
     highlightMV81Wins(r,wins);
     $("machineResult").textContent=`WIN +${fmt(win)} TOKENS`;
     playTone(win>=bet*20?"bigwin":"win");
     if(wins.length>1) toast(`✦ ${wins.length} VÝHERNÍCH CEST • +${fmt(win)} TOKENŮ`);
     else toast(`🎉 VÝHRA +${fmt(win)} TOKENŮ`);
   } else $("machineResult").textContent="NO WIN — TRY AGAIN";
   balance+=win;
 }else{
   for(let round=0;round<18;round++){reels.forEach(el=>el.innerHTML=symbolMarkup(current.symbols[Math.floor(Math.random()*current.symbols.length)]));reels.forEach(el=>el.classList.add("reel-spin"));await new Promise(r=>setTimeout(r,45+round*3));}
   reels.forEach(el=>el.classList.remove("reel-spin"));
   r=outcome();setReels(r);const win=calculateWin(r);balance+=win;
   if(win){$("machineResult").textContent=`WIN +${fmt(win)} TOKENS`;reels.slice(0,Math.min(6,reels.length)).forEach(el=>el.classList.add("reel-win"));toast(`🎉 VÝHRA +${fmt(win)} TOKENŮ`)}else $("machineResult").textContent="NO WIN — TRY AGAIN";
 }
 history.unshift({game:current.name,bet,win: isMV81()?calculateMV81(r).reduce((a,w)=>a+w.amount,0):calculateWin(r),time:new Date().toLocaleTimeString("cs-CZ",{hour:"2-digit",minute:"2-digit"})});
 history=history.slice(0,25);$("lastWin").textContent=fmt(isMV81()?calculateMV81(r).reduce((a,w)=>a+w.amount,0):calculateWin(r));updateBalances();spinning=false;$("spinBtn").disabled=false;
}

let simulationRunning=false;
function openSimulation(){
 if(!isMV81()){toast("RTP LAB je dostupný pro Multi Vegas 81");return}
 $("simBet").value=Math.max(1,Math.min(250,Math.round(bet)));
 $("simulationOverlay").classList.remove("hidden");
 $("simProgressBar").style.width="0%";
 $("simProgressText").textContent="Připraveno.";
 $("simResults").innerHTML="";
}
function closeSimulation(){if(!simulationRunning)$("simulationOverlay").classList.add("hidden")}
async function runSimulation(){
 if(simulationRunning)return;
 const wager=Math.max(1,Math.min(250,Math.round(Number($("simBet").value)||100)));
 const totalSpins=1000000;
 simulationRunning=true;
 $("runSimBtn").disabled=true;
 $("simProgressText").textContent="Simuluji skutečné spiny…";
 $("simResults").innerHTML="";
 let totalWon=0,totalWagered=0,hits=0,maxWin=0,maxMult=0;
 const started=performance.now();
 const chunk=5000;
 for(let start=0;start<totalSpins;start+=chunk){
   const end=Math.min(totalSpins,start+chunk);
   for(let i=start;i<end;i++){
     const r=outcomeMV81();
     const win=Math.min(wager*100,calculateMV81(r,wager).reduce((a,w)=>a+w.amount,0));
     totalWagered+=wager;
     totalWon+=win;
     if(win>0)hits++;
     if(win>maxWin)maxWin=win;
   }
   const pct=end/totalSpins*100;
   $("simProgressBar").style.width=pct.toFixed(1)+"%";
   $("simProgressText").textContent=`${end.toLocaleString("cs-CZ")} / ${totalSpins.toLocaleString("cs-CZ")} • ${pct.toFixed(1)} %`;
   await new Promise(requestAnimationFrame);
 }
 const rtp=totalWon/totalWagered*100;
 const net=totalWagered-totalWon;
 const elapsed=(performance.now()-started)/1000;
 const avgWin=totalWon/hits||0;
 $("simResults").innerHTML=`
   <div class="sim-grid">
    <div><small>SPINS</small><b>${fmt(totalSpins)}</b></div>
    <div><small>PROSÁZENO</small><b>${fmt(totalWagered)}</b></div>
    <div><small>VYPLACENO ZPĚT</small><b>${fmt(totalWon)}</b></div>
    <div><small>RTP</small><b class="${rtp>=89&&rtp<=91?"sim-good":"sim-warn"}">${rtp.toFixed(2)}%</b></div>
    <div><small>HOUSE EDGE</small><b>${(100-rtp).toFixed(2)}%</b></div>
    <div><small>HIT RATE</small><b>${(hits/totalSpins*100).toFixed(2)}%</b></div>
    <div><small>PRŮMĚRNÁ VÝHRA</small><b>${fmt(avgWin.toFixed(2))}</b></div>
    <div><small>MAX VÝHRA</small><b>${fmt(maxWin)} (${(maxWin/wager).toFixed(0)}×)</b></div>
    <div><small>ČISTO CASINO</small><b class="${net>=0?"sim-good":"sim-warn"}">${net>=0?"+":""}${fmt(net)}</b></div>
   </div>
   <div class="sim-note">Test trval ${elapsed.toFixed(1)} s. Výsledek je Monte Carlo simulace skutečného modelu Multi Vegas 81 v tomto demu. 1 000 000 spinů není garance budoucího výsledku.</div>`;
 $("simProgressText").textContent="Hotovo — 1 000 000 skutečně simulovaných spinů.";
 $("runSimBtn").disabled=false;
 simulationRunning=false;
}
function updateBalances(){$("balance").textContent=fmt(balance);$("gameBalance").textContent=fmt(balance)}
function setBet(v){if(v==="half")bet=Math.max(current.min,Math.floor(bet/2));else if(v==="min")bet=current.min;else bet=Math.min(current.max,Math.max(current.min,bet*v));updateBetUI()}
function adjustBet(dir){const step=Math.max(current.min,Math.round(bet*.25));bet=Math.max(current.min,Math.min(current.max,bet+dir*step));updateBetUI()}
function updateBetUI(){
 $("betValue").textContent=fmt(bet);$("machineBetLabel").textContent=fmt(bet);
 const maxMult=isMV81()?100:Math.max(...Object.values(current.payouts));
 $("maxWin").textContent=fmt(bet*maxMult);
}
function toggleSound(){sound=!sound;$("soundBtn").textContent=sound?"♫":"🔇";toast(sound?"SOUND ON":"SOUND OFF")}
function toggleFullscreen(){if(!document.fullscreenElement)$("gameOverlay").requestFullscreen?.();else document.exitFullscreen?.()}
function openPaytable(){
 const g=current||games[0];$("paytableTitle").textContent=g.name.toUpperCase();
 if(isMV81()){
   const order=["CHERRY","DOLLAR","ORANGE","PLUM","BELL","GRAPES","MELON","SEVEN","WILD"];
   const rows=order.map(s=>{const p=g.payouts[s];return `<div class="pay-row mv81-pay-row"><span class="pay-symbol"><img src="assets/games/mv81/${MV81_SYMBOLS[s].file}" alt="${s}"></span><span><b>${s==="WILD"?"MULTI WILD":MV81_SYMBOLS[s].label}</b><small>3 SYMBOLS / 4 SYMBOLS</small></span><b>${p?`x${p[3]} / x${p[4]}`:"—"}</b></div>`}).join("");
   const diagrams=MV81_PATTERNS_4.map((p,i)=>`<div class="mv81-line-card"><b>${i+1}</b><div>${Array.from({length:12},(_,k)=>{const c=k%4,row=Math.floor(k/4);return `<i class="${p[c]===row?"active":""}"></i>`}).join("")}</div></div>`).join("");
   $("paytableContent").innerHTML=`<div class="mv81-info"><strong>27 CRISS-CROSS WAYS</strong> for 3 matching symbols • <strong>81 WAYS</strong> for 4 matching symbols. Wins count from left to right. Multiple winning ways add together; only the highest win on a winning way counts. Multi Wild substitutes any symbol and multiplies a winning way ×2, ×4 or ×8.</div><div class="mv81-paytable">${rows}</div><h3 class="mv81-section-title">81 CRISS-CROSS WINNING WAYS</h3><div class="mv81-diagrams">${diagrams}</div><div class="pay-note">BET = total stake for the spin • 4 reels × 3 rows • Demo mechanics based on the published Multi Vegas 81 rules • calibrated demo RTP target 95% • max win 100× bet.</div>`;
 }else{
   $("paytableContent").innerHTML=Object.entries(g.payouts).map(([s,m])=>`<div class="pay-row"><span class="pay-symbol">${s}</span><span>3 × ${s}</span><b>x${m}</b></div>`).join("")+`<div class="pay-note">${g.layout} • ${g.lines} lines • RTP ${g.rtp}% • Min ${fmt(g.min)} • Max ${fmt(g.max)}</div>`;
 }
 $("paytableOverlay").classList.remove("hidden")
}
function closePaytable(){$("paytableOverlay").classList.add("hidden")}
function openRewards(){$("panelContent").innerHTML=`<div class="eyebrow gold">REWARDS</div><h2>FASTCASH <em>VIP</em></h2><div class="reward-level"><b>BRONZE</b><span>0 / 10,000 XP</span></div><div class="progress"><i style="width:18%"></i></div><div class="reward-grid"><div>♛<b>VIP TABLES</b><small>Coming soon</small></div><div>★<b>DAILY BONUS</b><small>250 tokens</small></div><div>◆<b>EXCLUSIVE SLOTS</b><small>Unlock at VIP</small></div></div>`;$("panelOverlay").classList.remove("hidden")}
function openStats(){const spins=history.length,wins=history.reduce((a,x)=>a+x.win,0),bets=history.reduce((a,x)=>a+x.bet,0);$("panelContent").innerHTML=`<div class="eyebrow gold">PLAYER STATS</div><h2>YOUR <em>SESSION</em></h2><div class="stats-big"><div><b>${spins}</b><small>SPINS</small></div><div><b>${fmt(bets)}</b><small>WAGERED</small></div><div><b>${fmt(wins)}</b><small>WON</small></div></div><h3>RECENT SPINS</h3><div class="history">${history.length?history.map(x=>`<div><span>${x.game}</span><small>${x.time}</small><b class="${x.win?'win':''}">${x.win?"+":""}${fmt(x.win-x.bet)}</b></div>`).join(""):"No spins yet."}</div>`;$("panelOverlay").classList.remove("hidden")}
function openHelp(){$("panelContent").innerHTML=`<div class="eyebrow gold">HELP</div><h2>HOW TO <em>PLAY</em></h2><div class="help"><p><b>1.</b> Choose a slot from the lobby.</p><p><b>2.</b> Set your bet with −/+ or quick bets.</p><p><b>3.</b> Press SPIN and complete a winning line.</p><p><b>4.</b> Use +10,000 at the top while testing the demo.</p></div>`;$("panelOverlay").classList.remove("hidden")}
function closePanel(){$("panelOverlay").classList.add("hidden")}
function claimDaily(){if(dailyClaimed){toast("DNEŠNÍ ODMĚNA UŽ BYLA VYZVEDNUTA");return}dailyClaimed=true;balance+=250;updateBalances();toast("🎁 +250 TOKENŮ — DAILY REWARD")}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2500)}
const ticker=["Mikey hit 2,500 tokens on Lucky Sevens","Vinnie won 8,000 tokens on Diamond Rush","Sofia hit a 3x jackpot on Ocean Drive","Tony just spun High Roller for 5,000","CJ won 1,250 tokens on Blazing Fruits"];let ti=0;setInterval(()=>{ti=(ti+1)%ticker.length;$("tickerText").textContent=ticker[ti]},4000);
renderGames();updateBalances();


/* =========================
   FASTCASH TEXAS HOLD'EM ENGINE
   ========================= */
const poker = {
  players:[
    {name:"LUNA",stack:2000,seat:0,bot:true},
    {name:"MARCUS",stack:2000,seat:1,bot:true},
    {name:"YOU",stack:2000,seat:2,bot:false},
    {name:"NICO",stack:2000,seat:3,bot:true},
    {name:"SOPHIE",stack:2000,seat:4,bot:true}
  ],
  deck:[],community:[],pot:0,street:"waiting",dealer:0,turn:null,currentBet:0,minRaise:100,folded:new Set(),contrib:[0,0,0,0,0],hole:[[],[],[],[],[]],handId:0,active:false,acting:false
};
const pokerRankMap={ "2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"J":11,"Q":12,"K":13,"A":14 };
const pokerSuits=["♠","♥","♦","♣"], pokerRanks=["2","3","4","5","6","7","8","9","10","J","Q","K","A"];

function pokerCard(rank,suit){return {rank,suit,value:pokerRankMap[rank]}}
function pokerNewDeck(){
  const d=[]; for(const s of pokerSuits) for(const r of pokerRanks)d.push(pokerCard(r,s));
  for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}
  return d;
}
function pokerCardHTML(c,back=false){
  if(back)return '<div class="card back"></div>';
  const red=(c.suit==="♥"||c.suit==="♦")?"red":"";
  return `<div class="card ${red}"><span class="rank">${c.rank}</span><span class="suit">${c.suit}</span></div>`;
}
function pokerBestFive(cards){
  let best=null;
  function scoreFive(a){
    const vals=a.map(c=>c.value).sort((x,y)=>y-x), counts={};
    vals.forEach(v=>counts[v]=(counts[v]||0)+1);
    const groups=Object.entries(counts).map(([v,n])=>({v:+v,n})).sort((x,y)=>y.n-x.n||y.v-x.v);
    const flush=a.every(c=>c.suit===a[0].suit);
    const uniq=[...new Set(vals)].sort((x,y)=>y-x);
    let straightHigh=0;
    if(uniq.length===5){ if(uniq[0]-uniq[4]===4)straightHigh=uniq[0]; else if(uniq.join(",")==="14,5,4,3,2")straightHigh=5; }
    if(flush&&straightHigh)return [8,straightHigh];
    if(groups[0].n===4)return [7,groups[0].v,groups[1].v];
    if(groups[0].n===3&&groups[1].n===2)return [6,groups[0].v,groups[1].v];
    if(flush)return [5,...vals];
    if(straightHigh)return [4,straightHigh];
    if(groups[0].n===3)return [3,groups[0].v,...groups.slice(1).map(x=>x.v).sort((a,b)=>b-a)];
    const pairs=groups.filter(x=>x.n===2).sort((a,b)=>b.v-a.v);
    if(pairs.length>=2)return [2,pairs[0].v,pairs[1].v,groups.find(x=>x.n===1).v];
    if(pairs.length===1)return [1,pairs[0].v,...groups.filter(x=>x.n===1).map(x=>x.v).sort((a,b)=>b-a)];
    return [0,...vals];
  }
  const combos=(arr,k,start=0,prefix=[],out=[])=>{
    if(prefix.length===k){out.push(prefix.map(i=>arr[i]));return out}
    for(let i=start;i<=arr.length-(k-prefix.length);i++)combos(arr,k,i+1,prefix.concat(i),out); return out
  };
  for(const five of combos(cards,5)){const s=scoreFive(five);if(!best||compareScores(s,best.score)>0)best={score:s,cards:five}}
  return best;
}
function compareScores(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x-y}return 0}
function pokerHandName(score){
  return ["High Card","One Pair","Two Pair","Three of a Kind","Straight","Flush","Full House","Four of a Kind","Straight Flush","Royal Flush"][score[0]==8&&score[1]===14?9:score[0]];
}
function pokerSyncBalance(flash=true){
  balance=Math.max(0,Math.floor(Number(poker.players[2].stack)||0));
  updateBalances();
  if(flash){
    ["balance","gameBalance"].forEach(id=>{
      const el=document.getElementById(id);
      if(el){el.classList.remove("poker-balance-flash");void el.offsetWidth;el.classList.add("poker-balance-flash");}
    });
  }
}
function pokerResetSeats(){
  poker.players.forEach((p,i)=>{
    if(i===2) p.stack=Math.max(0,Math.floor(balance));
    else p.stack=Math.max(p.stack,2000);
    p.folded=false;p.allin=false;
    document.getElementById("stack"+i).textContent=p.stack.toLocaleString("cs-CZ");
    document.getElementById("cards"+i).innerHTML="";
    document.getElementById("badge"+i).textContent="";
    document.getElementById("seat"+i).classList.remove("folded","winner","active");
  });
}

function openPoker(){
  poker.players[2].stack=Math.max(0,Math.floor(balance));
  document.getElementById("pokerOverlay").classList.remove("hidden");
  document.body.classList.add("poker-open");
  pokerSpeak("Welcome to FastCash. Five seats, one winner.");
  pokerMessage("Table is ready. Press DEAL.");
  pokerUpdateActions(false);
}
function closePoker(){document.getElementById("pokerOverlay").classList.add("hidden");document.body.classList.remove("poker-open")}
function openPokerRules(){document.getElementById("pokerRulesOverlay").classList.remove("hidden")}
function closePokerRules(){document.getElementById("pokerRulesOverlay").classList.add("hidden")}
function pokerMessage(t){const e=document.getElementById("pokerMessage");if(e)e.textContent=t}
function pokerSpeak(t,anim=""){const e=document.getElementById("dealerSpeech");if(e)e.textContent=t;const a=document.getElementById("dealerAvatar");if(a){a.classList.remove("deal","win");if(anim){void a.offsetWidth;a.classList.add(anim)}}}
function pokerDealCard(playerIndex,hidden=false){
  const c=poker.deck.pop(); poker.hole[playerIndex].push(c);
  document.getElementById("cards"+playerIndex).insertAdjacentHTML("beforeend",pokerCardHTML(c,hidden));
}
function pokerStartHand(){
  if(balance<50){
    pokerMessage("Nemáš dostatek tokenů na blind.");
    pokerSpeak("Na stůl potřebuješ alespoň 50 tokenů.");
    pokerUpdateActions(false);
    return;
  }
  poker.players[2].stack=Math.floor(balance);
  poker.handId++;poker.deck=pokerNewDeck();poker.community=[];poker.pot=0;poker.street="preflop";poker.currentBet=100;poker.minRaise=100;poker.folded=new Set();poker.contrib=[0,0,0,0,0];poker.hole=[[],[],[],[],[]];poker.active=true;poker.acting=true;
  poker.players.forEach((p,i)=>{p.folded=false;p.allin=false;document.getElementById("seat"+i).classList.remove("folded","winner","active");document.getElementById("cards"+i).innerHTML="";document.getElementById("badge"+i).textContent=""});
  poker.dealer=(poker.dealer+1)%5;
  const sb=(poker.dealer+1)%5, bb=(poker.dealer+2)%5;
  pokerBet(sb,50);pokerBet(bb,100);
  for(let r=0;r<2;r++)for(let i=0;i<5;i++)pokerDealCard(i,i!==2);
  pokerRender();pokerSpeak("Karty jsou rozdány. Začínáme po velké sázce.","deal");pokerMessage("Pre-flop — jsi na tahu.");
  poker.turn=(bb+1)%5;pokerSetTurn();
}

function pokerBet(i,amount){
  const p=poker.players[i];
  const actual=Math.min(Math.max(0,amount),p.stack);
  if(actual<=0)return 0;
  p.stack-=actual;
  poker.contrib[i]+=actual;
  poker.pot+=actual;
  if(p.stack===0)p.allin=true;
  if(i===2) pokerSyncBalance(true);
  return actual;
}

function pokerSetTurn(){
  if(!poker.active)return;
  let loops=0;while(loops++<10 && (poker.folded.has(poker.turn)||poker.players[poker.turn].allin))poker.turn=(poker.turn+1)%5;
  document.querySelectorAll(".seat").forEach(e=>e.classList.remove("active"));
  document.getElementById("seat"+poker.turn).classList.add("active");
  document.getElementById("actionGlow").classList.add("on");
  document.getElementById("pokerTurnText").textContent=poker.turn===2?"YOUR TURN":"Waiting for "+poker.players[poker.turn].name;
  pokerUpdateActions(poker.turn===2);
  if(poker.turn!==2)setTimeout(pokerBotAction,650+Math.random()*650);
}
function pokerBotAction(){
  if(!poker.active||poker.turn===2)return;
  const i=poker.turn,p=poker.players[i],toCall=Math.max(0,poker.currentBet-poker.contrib[i]),strength=Math.random();
  let action="fold";
  if(strength>.18) action=toCall?"call":"check";
  if(strength>.72 && p.stack>poker.currentBet) action="raise";
  pokerDoAction(i,action);
}
function pokerAction(action){
  if(!poker.active||poker.turn!==2)return;
  pokerDoAction(2,action);
}
function pokerDoAction(i,action){
  if(!poker.active||i!==poker.turn)return;
  const p=poker.players[i],toCall=Math.max(0,poker.currentBet-poker.contrib[i]);
  if(action==="fold"){p.folded=true;poker.folded.add(i);document.getElementById("seat"+i).classList.add("folded");document.getElementById("badge"+i).textContent="FOLDED";pokerSpeak(i===2?"Folded.":p.name+" folds.");}
  else if(action==="check"&&toCall===0){document.getElementById("badge"+i).textContent="CHECK";pokerSpeak(i===2?"Check.":p.name+" checks.");}
  else if(action==="call"){const amt=Math.min(toCall,p.stack);pokerBet(i,amt);document.getElementById("badge"+i).textContent="CALL "+amt;}
  else if(action==="raise"){const raiseTo=Math.min(p.stack+poker.contrib[i],Math.max(poker.currentBet+poker.minRaise,Number(document.getElementById("raiseSlider").value)));const amt=raiseTo-poker.contrib[i];if(amt>0){pokerBet(i,amt);poker.currentBet=raiseTo;poker.minRaise=Math.max(100,raiseTo-poker.currentBet+amt);document.getElementById("badge"+i).textContent="RAISE "+raiseTo;pokerSpeak(i===2?"Raise.":p.name+" raises.");}}
  else if(action==="allin"){const amt=p.stack;pokerBet(i,amt);poker.currentBet=Math.max(poker.currentBet,poker.contrib[i]);poker.players[i].allin=true;document.getElementById("badge"+i).textContent="ALL-IN";pokerSpeak(i===2?"All-in.":p.name+" moves all-in.");}
  pokerRender();
  const live=poker.players.filter((_,idx)=>!poker.folded.has(idx));
  if(live.length===1){pokerAward(live[0]);return}
  pokerAdvanceTurn();
}
function pokerAdvanceTurn(){
  const oldStreet=poker.street;
  // End betting round after everyone has matched current bet or is all-in.
  const live=poker.players.map((p,i)=>i).filter(i=>!poker.folded.has(i));
  const roundDone=live.every(i=>poker.players[i].allin||poker.contrib[i]===poker.currentBet);
  if(roundDone){
    if(poker.street==="preflop"){poker.street="flop";poker.currentBet=0;poker.contrib=poker.contrib.map(()=>0);poker.community.push(poker.deck.pop(),poker.deck.pop(),poker.deck.pop());pokerSpeak("Flop is on the table.","deal")}
    else if(poker.street==="flop"){poker.street="turn";poker.currentBet=0;poker.contrib=poker.contrib.map(()=>0);poker.community.push(poker.deck.pop());pokerSpeak("Turn card.");}
    else if(poker.street==="turn"){poker.street="river";poker.currentBet=0;poker.contrib=poker.contrib.map(()=>0);poker.community.push(poker.deck.pop());pokerSpeak("River. Last card.");}
    else {pokerShowdown();return}
    pokerRender();poker.turn=(poker.dealer+1)%5;pokerSetTurn();return
  }
  poker.turn=(poker.turn+1)%5;pokerSetTurn();
}
function pokerShowdown(){
  poker.acting=false;
  const live=poker.players.map((p,i)=>i).filter(i=>!poker.folded.has(i));
  let best=null,winners=[];
  live.forEach(i=>{const result=pokerBestFive(poker.community.concat(poker.hole[i]));if(!best||compareScores(result.score,best.score)>0){best=result;winners=[i]}else if(compareScores(result.score,best.score)===0)winners.push(i)});
  const share=Math.floor(poker.pot/winners.length),remainder=poker.pot-share*winners.length;
  winners.forEach((i,k)=>{poker.players[i].stack+=share+(k===0?remainder:0);document.getElementById("seat"+i).classList.add("winner");document.getElementById("badge"+i).textContent="VÝHRA • "+pokerHandName(best.score);}); if(winners.includes(2)) pokerSyncBalance(true);
  pokerSpeak(winners.includes(2)?"Beautiful hand. You take the pot!":poker.players[winners[0]].name+" takes the pot.", "win");
  pokerMessage("Showdown — "+winners.map(i=>poker.players[i].name).join(" / ")+" wins.");
  pokerRender(true);poker.active=false;pokerUpdateActions(false);
  document.getElementById("dealPokerBtn").textContent="DEAL AGAIN";
}
function pokerAward(i){poker.players[i].stack+=poker.pot; if(i===2) pokerSyncBalance(true); document.getElementById("seat"+i).classList.add("winner");document.getElementById("badge"+i).textContent="VÝHRA • VŠICHNI FOLD";pokerSpeak(poker.players[i].name+" wins — everyone folded.","win");pokerMessage("Hand over.");poker.active=false;pokerRender(true);pokerUpdateActions(false);document.getElementById("dealPokerBtn").textContent="DEAL AGAIN"}
function dealPoker(){if(poker.active)return;pokerResetSeats();document.getElementById("dealPokerBtn").textContent="DEAL";pokerStartHand()}
function pokerRender(showdown=false){
  document.getElementById("pokerPot").textContent=poker.pot.toLocaleString("cs-CZ");
  document.getElementById("streetLabel").textContent=({waiting:"WAITING FOR DEAL",preflop:"PRE-FLOP",flop:"FLOP",turn:"TURN",river:"RIVER"}[poker.street]||"SHOWDOWN");
  document.getElementById("communityCards").innerHTML=poker.community.map(c=>pokerCardHTML(c)).join("");
  poker.players.forEach((p,i)=>{
    document.getElementById("stack"+i).textContent=p.stack.toLocaleString("cs-CZ");
    const holder=document.getElementById("cards"+i);
    if(i===2||showdown)holder.innerHTML=poker.hole[i].map(c=>pokerCardHTML(c)).join("");
    else if(poker.hole[i].length)holder.innerHTML=poker.hole[i].map(()=>pokerCardHTML(null,true)).join("");
  });
  if(poker.turn===2 && poker.active){const toCall=Math.max(0,poker.currentBet-poker.contrib[2]);document.getElementById("callAmount").textContent=toCall.toLocaleString("cs-CZ");document.getElementById("pokerHandText").textContent=poker.hole[2].length?"Holding "+poker.hole[2].map(c=>c.rank+c.suit).join(" "):"You are holding —";} 
  else if(poker.hole[2].length)document.getElementById("pokerHandText").textContent="Holding "+poker.hole[2].map(c=>c.rank+c.suit).join(" ");
}
function pokerUpdateActions(enabled){
  const ids=["pokerFold","pokerCheck","pokerCall","pokerRaise","pokerAllin"];
  ids.forEach(id=>{const e=document.getElementById(id);if(e)e.disabled=!enabled});
  const toCall=poker.active?Math.max(0,poker.currentBet-poker.contrib[2]):0;
  document.getElementById("pokerCheck").disabled=!enabled||toCall>0;
  document.getElementById("pokerCall").disabled=!enabled||toCall===0;
  document.getElementById("callAmount").textContent=toCall.toLocaleString("cs-CZ");
}
function updateRaisePreview(v){document.getElementById("raisePreview").textContent=Number(v).toLocaleString("cs-CZ");document.getElementById("raiseAmount").textContent=Number(v).toLocaleString("cs-CZ")}
function pokerDoNotScroll(e){if(e) e.preventDefault()}

/* ===== GTA POKER PRESENTATION / CHIP ANIMATION ===== */
const _pokerSpeakOriginal = pokerSpeak;
pokerSpeak = function(t,anim=""){
  const cz = {
    "Welcome to FastCash.":"Vítejte u stolu.",
    "Cards are in. Action starts after the big blind.":"Karty jsou rozdány. Začínáme po velké sázce.",
    "Flop is on the table.":"Flop je na stole.",
    "Turn card.":"Turnová karta.",
    "River. Last card.":"River. Poslední karta.",
    "Beautiful hand. You take the pot!":"Výborná kombinace. Berete bank!",
  };
  let msg=cz[t]||t;
  if(/folds\./.test(msg)) msg=msg.replace("folds.","se skládá.");
  if(/checks\./.test(msg)) msg=msg.replace("checks.","check.");
  if(/raises\./.test(msg)) msg=msg.replace("raises.","navyšuje.");
  if(/moves all-in\./.test(msg)) msg=msg.replace("moves all-in.","jde all-in.");
  if(/takes the pot\./.test(msg)) msg=msg.replace("takes the pot.","bere bank.");
  const e=document.getElementById("dealerSpeech"); if(e)e.textContent=msg;
  const a=document.getElementById("dealerAvatar"); if(a){a.classList.remove("deal","win"); if(anim){void a.offsetWidth;a.classList.add(anim)}}
};

function animatePokerChips(amount){
  const pile=document.getElementById("chipPile");
  const potChips=document.getElementById("potChips");
  if(!pile)return;
  const count=Math.max(3,Math.min(14,Math.ceil(amount/100)));
  for(let i=0;i<count;i++){
    const c=document.createElement("i"); c.className="chip";
    const hues=["#d9414d","#e8c44a","#4b83c6","#e9e9e9"];
    c.style.background=`radial-gradient(circle at 35% 30%,#fff 0 8%,${hues[i%4]} 9% 70%,#16191d 71%)`;
    c.style.setProperty("--sx",(Math.random()*160-80)+"px");
    c.style.setProperty("--sy",(Math.random()*100-50)+"px");
    c.style.setProperty("--ex",(Math.random()*40-20)+"px");
    c.style.setProperty("--ey",(i%5)*-5+"px");
    c.style.left=(46+i%5*7)+"px"; c.style.top=(16+Math.floor(i/5)*7)+"px";
    pile.appendChild(c);
    setTimeout(()=>c.remove(),1600);
  }
  if(potChips){
    const n=Math.max(4,Math.min(18,Math.ceil(poker.pot/150)));
    potChips.innerHTML="";
    for(let i=0;i<n;i++){
      const s=document.createElement("i");
      s.style.background=["#d9414d","#e8c44a","#4b83c6","#e9e9e9"][i%4];
      s.style.transform=`translateY(${-Math.floor(i/6)*3}px)`;
      potChips.appendChild(s);
    }
  }
}
const _pokerBetOriginal = pokerBet;
pokerBet = function(i,amount){
  _pokerBetOriginal(i,amount);
  if(amount>0) animatePokerChips(amount);
};

/* Poker visual v2: force Czech labels and animate chip stacks after every bet. */
(function(){
  const cz={
    "Pre-flop — your move.":"Pre-flop — jsi na tahu.",
    "Showdown — ":"Showdown — ",
    "Hand over.":"Konec hry.",
    "Table is ready. Press DEAL.":"Stůl je připraven. Stiskni ROZDAT.",
    "Press DEAL to start":"Stiskni ROZDAT pro začátek."
  };
  window.pokerMessageCZ=function(t){ const e=document.getElementById("pokerMessage"); if(e)e.textContent=cz[t]||t; };
})();

/* V5 UI safety: keep the visible HUD in Czech. */
(function(){
  const _oldSetTurn = window.pokerSetTurn;
  if(typeof _oldSetTurn === "function"){
    window.pokerSetTurn = function(){
      _oldSetTurn();
      const t=document.getElementById("pokerTurnText");
      if(t && window.poker && poker.active){
        t.textContent = poker.turn===2 ? "TVŮJ TAH" : "TAH MÁ "+poker.players[poker.turn].name;
      }
    };
  }
})();

/* V7: dealer speech remains a single readable line. */
(function(){
  const e=document.getElementById("dealerSpeech");
  if(e){
    e.style.whiteSpace="nowrap";
    e.style.overflow="hidden";
    e.style.textOverflow="ellipsis";
  }
})();

/* ==========================================================
   POKER LIVE LAYOUT EDITOR — robust drag/scale version
   - opens automatically whenever poker opens
   - explicit OFF button lets the user test the real game
   - dealer and table have priority hit-testing so they are always draggable
   - wheel / +/- scales the selected object, including the table
   - center crosshair marks the exact editor center
   ========================================================== */
(function(){
  const KEY='fastcash_poker_live_layout_v4_json';
  const IMPORTED_LAYOUT_V3 = {"version":3,"stage":{"width":1448,"height":502},"items":{"LUNA":{"selector":"#seat0","x":23.1523,"y":5.8297,"scale":0.75},"MARCUS":{"selector":"#seat1","x":91.0798,"y":81.0804,"scale":0.75},"TY":{"selector":"#seat2","x":50.6153,"y":100.2948,"scale":0.75},"NICO":{"selector":"#seat3","x":9.0583,"y":80.4435,"scale":0.75},"SOPHIE":{"selector":"#seat4","x":78.1647,"y":7.7079,"scale":0.75},"TABLE LOGO":{"selector":"#pokerOverlay .table-logo","x":50,"y":50.4851,"scale":1},"POT":{"selector":"#pokerOverlay .pot-display","x":50.3314,"y":23.0466,"scale":1},"POT CHIPS":{"selector":"#pokerOverlay .pot-chips","x":50.1855,"y":47.1566,"scale":1},"COMMUNITY CARDS":{"selector":"#communityCards","x":50.636,"y":49.7637,"scale":0.85},"STREET":{"selector":"#streetLabel","x":61.624,"y":87.1875,"scale":1},"ACTION GLOW":{"selector":"#actionGlow","x":49.282,"y":82.9498,"scale":1},"HUD":{"selector":"#pokerOverlay .poker-hud-v5","x":50,"y":111.7416,"scale":1},"YOUR INFO":{"selector":"#pokerOverlay .your-info","x":9.1135,"y":111.8212,"scale":1},"ACTIONS":{"selector":"#pokerOverlay .poker-actions","x":46.8931,"y":111.8212,"scale":1},"FOLD":{"selector":"#pokerFold","x":32.4979,"y":111.8212,"scale":1},"CHECK":{"selector":"#pokerCheck","x":39.3331,"y":111.8212,"scale":1},"CALL":{"selector":"#pokerCall","x":46.4966,"y":111.8212,"scale":1},"RAISE":{"selector":"#pokerRaise","x":54.0562,"y":111.8212,"scale":1},"ALL-IN":{"selector":"#pokerAllin","x":61.2875,"y":111.8212,"scale":1},"RAISE CONTROL":{"selector":"#pokerOverlay .raise-control","x":87.7796,"y":111.8212,"scale":1},"SLIDER":{"selector":"#raiseSlider","x":83.0848,"y":113.0749,"scale":1},"RAISE VALUE":{"selector":"#raisePreview","x":90.6794,"y":111.8212,"scale":1},"DEAL":{"selector":"#dealPokerBtn","x":95.5123,"y":111.8212,"scale":1},"BOTTOMLINE":{"selector":"#pokerOverlay .poker-bottomline","x":50,"y":128.7196,"scale":1}}};
  let drag=null, selected=null;
  const targets=[
    ['pokerOverlay .poker-topbar','TOPBAR'],['pokerOverlay .poker-title','TITLE'],['pokerOverlay .poker-top-actions','TOP ACTIONS'],
    ['pokerOverlay .poker-dealer','DEALER'],['pokerOverlay .poker-table-v5','TABLE'],
    ['#seat0','LUNA'],['#seat1','MARCUS'],['#seat2','TY'],['#seat3','NICO'],['#seat4','SOPHIE'],
    ['#pokerOverlay .table-logo','TABLE LOGO'],['#pokerOverlay .pot-display','POT'],['#pokerOverlay .pot-chips','POT CHIPS'],
    ['#communityCards','COMMUNITY CARDS'],['#streetLabel','STREET'],['#actionGlow','ACTION GLOW'],['#pokerOverlay .poker-hud-v5','HUD'],
    ['#pokerOverlay .your-info','YOUR INFO'],['#pokerOverlay .poker-actions','ACTIONS'],
    ['#pokerFold','FOLD'],['#pokerCheck','CHECK'],['#pokerCall','CALL'],['#pokerRaise','RAISE'],['#pokerAllin','ALL-IN'],
    ['#pokerOverlay .raise-control','RAISE CONTROL'],['#raiseSlider','SLIDER'],['#raisePreview','RAISE VALUE'],['#dealPokerBtn','DEAL'],
    ['#pokerOverlay .poker-bottomline','BOTTOMLINE']
  ];
  function el(sel){return document.querySelector(sel)}
  function stage(){return document.getElementById('pokerStage')}
  function status(t){const e=el('#pokerEditorStatus');if(e)e.textContent=t}
  function updateScaleLabel(){const e=el('#pokerEditorScale'); if(e)e.textContent=selected?Math.round((Number(selected.dataset.editorScale)||1)*100)+'%':'100%'}
  function baseTransform(e){const s=Number(e.dataset.editorScale)||1; e.style.setProperty('transform',`translate(-50%,-50%) scale(${s})`,'important')}
  function markTargets(){
    targets.forEach(([sel,name])=>{
      const e=el(sel); if(!e||e.dataset.editorTarget==='1')return;
      e.dataset.editorTarget='1'; e.dataset.editorName=name; e.dataset.editorScale=e.dataset.editorScale||'1'; e.title='EDITOR: '+name;
      e.addEventListener('click',()=>select(e),true);
      e.addEventListener('wheel',scaleWheel,{passive:false});
    });
  }
  function select(e){if(selected)selected.classList.remove('editor-selected');selected=e||null;if(selected)selected.classList.add('editor-selected');updateScaleLabel();status(selected?'VYBRÁNO: '+(selected.dataset.editorName||selected.id||'OBJ'):'EDITOR AKTIVNÍ')}
  function pointerInside(e,x,y){const r=e.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
  function pickTarget(ev){
    const s=stage(); if(!s)return null;
    const ov=el('#pokerOverlay');
    if(!ov?.classList.contains('editor-mode'))return null;
    if(ev.target?.closest?.('.poker-editor-ui'))return null;
    /* Children get first chance; then the whole table/dealer. */
    const priority=[...targets].map(([sel])=>el(sel)).filter(Boolean);
    const special=priority.filter(e=>e.matches?.('.poker-dealer,.poker-table-v5'));
    const normal=priority.filter(e=>!e.matches?.('.poker-dealer,.poker-table-v5')).reverse();
    for(const e of normal){if(pointerInside(e,ev.clientX,ev.clientY))return e}
    for(const e of special){if(pointerInside(e,ev.clientX,ev.clientY))return e}
    return null;
  }
  function startDrag(ev){
    const e=pickTarget(ev); if(!e)return;
    const s=stage(); if(!s)return;
    ev.preventDefault(); ev.stopPropagation(); select(e);
    const parent=s, r=parent.getBoundingClientRect(), er=e.getBoundingClientRect();
    e.style.setProperty('position','absolute','important');
    drag={e,r,dx:ev.clientX-(er.left+er.width/2),dy:ev.clientY-(er.top+er.height/2)};
    try{s.setPointerCapture?.(ev.pointerId)}catch(_){ }
    window.addEventListener('pointermove',moveDrag,{passive:false});
    window.addEventListener('pointerup',endDrag,{once:true});
  }
  function moveDrag(ev){
    if(!drag)return; ev.preventDefault();
    const {e,r,dx,dy}=drag;
    let x=((ev.clientX-r.left-dx)/r.width)*100, y=((ev.clientY-r.top-dy)/r.height)*100;
    x=Math.max(-30,Math.min(130,x)); y=Math.max(-30,Math.min(130,y));
    e.style.setProperty('left',x+'%','important'); e.style.setProperty('top',y+'%','important');
    e.style.setProperty('right','auto','important'); e.style.setProperty('bottom','auto','important');
    baseTransform(e); e.dataset.editorX=x.toFixed(4); e.dataset.editorY=y.toFixed(4);
  }
  function endDrag(){if(!drag)return;drag=null;pokerEditorSave(false);window.removeEventListener('pointermove',moveDrag)}
  function setScale(e,val){if(!e)return;val=Math.max(.15,Math.min(3,val));e.dataset.editorScale=val.toFixed(3);baseTransform(e);updateScaleLabel();pokerEditorSave(false)}
  function scaleWheel(ev){
    const ov=el('#pokerOverlay');if(!ov||!ov.classList.contains('editor-mode'))return;
    ev.preventDefault();ev.stopPropagation();select(ev.currentTarget);
    setScale(ev.currentTarget,(Number(ev.currentTarget.dataset.editorScale)||1)+(ev.deltaY<0?.05:-.05));
  }
  window.pokerEditorScale=function(delta){if(!selected){status('NEJDŘÍV KLIKNI NA OBJEKT');return}setScale(selected,(Number(selected.dataset.editorScale)||1)+delta)};
  window.pokerEditorCenter=function(){
    if(!selected){status('NEJDŘÍV KLIKNI NA OBJEKT');return}
    selected.style.setProperty('left','50%','important');selected.style.setProperty('top','50%','important');
    selected.style.setProperty('right','auto','important');selected.style.setProperty('bottom','auto','important');
    baseTransform(selected);selected.dataset.editorX='50';selected.dataset.editorY='50';pokerEditorSave(false);status('OBJEKT V CENTRU ✓')
  };
  function getData(){
    markTargets();const s=stage(),out={version:3,stage:{width:s?.clientWidth||0,height:s?.clientHeight||0},items:{}};
    targets.forEach(([sel,name])=>{const e=el(sel);if(!e)return;const r=e.getBoundingClientRect(),pr=s.getBoundingClientRect();
      const x=e.dataset.editorX!==undefined?Number(e.dataset.editorX):((r.left+r.width/2-pr.left)/pr.width)*100;
      const y=e.dataset.editorY!==undefined?Number(e.dataset.editorY):((r.top+r.height/2-pr.top)/pr.height)*100;
      out.items[name]={selector:sel,x:Number(x.toFixed(4)),y:Number(y.toFixed(4)),scale:Number((Number(e.dataset.editorScale)||1).toFixed(3))}
    });return out
  }
  function applyData(data){if(!data?.items)return;markTargets();targets.forEach(([sel,name])=>{const e=el(sel),d=data.items[name];if(!e||!d)return;
    e.style.setProperty('position','absolute','important');e.style.setProperty('left',d.x+'%','important');e.style.setProperty('top',d.y+'%','important');e.style.setProperty('right','auto','important');e.style.setProperty('bottom','auto','important');
    e.dataset.editorX=d.x;e.dataset.editorY=d.y;e.dataset.editorScale=d.scale||1;baseTransform(e)
  })}
  window.pokerEditorSave=function(show=true){try{localStorage.setItem(KEY,JSON.stringify(getData(),null,2));if(show)status('ULOŽENO ✓')}catch(e){status('CHYBA ULOŽENÍ')}};
  window.pokerEditorReset=function(){localStorage.removeItem(KEY);location.reload()};
  window.pokerEditorExport=function(){const blob=new Blob([JSON.stringify(getData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='poker-layout-editor.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('JSON EXPORT ✓')};
  window.pokerEditorUseImported=function(){try{localStorage.setItem(KEY,JSON.stringify(IMPORTED_LAYOUT_V3));applyData(IMPORTED_LAYOUT_V3);status('IMPORTOVANÝ LAYOUT ✓')}catch(e){status('CHYBA LAYOUTU')}};
  window.pokerEditorEnable=function(){const ov=el('#pokerOverlay');if(!ov)return;ov.classList.add('editor-mode');markTargets();try{const raw=localStorage.getItem(KEY);if(raw)applyData(JSON.parse(raw));else applyData(IMPORTED_LAYOUT_V3)}catch(e){applyData(IMPORTED_LAYOUT_V3)}updateScaleLabel();status('EDITOR AKTIVNÍ')};
  window.pokerEditorDisable=function(){const ov=el('#pokerOverlay');if(!ov)return;pokerEditorSave(false);ov.classList.remove('editor-mode');if(selected)selected.classList.remove('editor-selected');selected=null;status('EDITOR VYPNUTÝ — HRA');updateScaleLabel()};
  const oldOpen=window.openPoker;window.openPoker=function(){if(typeof oldOpen==='function')oldOpen();setTimeout(()=>window.pokerEditorEnable(),80)};
  const oldClose=window.closePoker;window.closePoker=function(){pokerEditorSave(false);window.pokerEditorDisable();if(typeof oldClose==='function')oldClose()};
  document.addEventListener('DOMContentLoaded',()=>{
    markTargets();
    const s=stage();
    if(s)s.addEventListener('pointerdown',startDrag,{capture:true,passive:false});
    window.addEventListener('keydown',e=>{if(e.key==='Escape'&&el('#pokerOverlay')?.classList.contains('editor-mode'))pokerEditorDisable()});
  });
})();

